### ISSUE TITLE
hard negative mining

### ISSUE THREAD

**Issue by prayshe** [kensun0/Joint_Cascade_Face_Detection_And_Alignment#1]
Hi,

Can you explain what is hard negative sample mining mentioned in Algorithm 3 on the original paper? And where do you perform this mining on your code? Thanks!

**Comment by kensun0** [comment]
Assume that you have tained the first tree, now you want to train the second. The two trees are cascaded. You should not use samples which can not pass(be classified negative) the first tree to training the second tree, because these samples never meet the second tree, it is in vain. So you need to exclude these negative samples, and add (mining) some new(hard) negative samplse which can pass the first tree. 

The code is placed in "randomforest.cpp"   from line 146 to line 210.

**Comment by prayshe** [comment]
Thank you for your help!
